version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webserver:
    # image: apache/airflow:2.9.1
    image: apache/airflow:slim-2.5.0rc2-python3.10
    # command: bash -c "pip install -r /requirements.txt && airflow db init && airflow webserver"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    entrypoint: /bin/bash -c "pip install -r /requirements.txt && airflow db init && airflow webserver"

  scheduler:
    image: apache/airflow:2.9.1
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    depends_on:
      - webserver
      - postgres
    entrypoint: /bin/bash -c "pip install -r /requirements.txt && airflow scheduler"

  # airflow-init:
  #   image: apache/airflow:2.9.1
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./logs:/opt/airflow/logs
  #     - ./plugins:/opt/airflow/plugins
  #     - ./requirements.txt:/requirements.txt

  #   entrypoint: /bin/bash -c "pip install -r /requirements.txt && airflow db init"
  #   depends_on:
  #     - postgres

volumes:
  postgres_data: